### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by marco9446** [ASQ-USI/question-editor-asq#5]
#### User scenario 1 "basic"

A user:
- [x] 1) should be able to drag and drop a new asq-text-input-q to the canvas
- [x] 2) should be able to change the text of the label
- [x] 3) should be able to specify a solution
#### User scenario 2 "stats"

A user:
- [x] 1) should be able to everything in schenario-1
- [x] 2) should be able to specify an asq-text-input-q-stats element that is linked to asq-text-input-q
#### User scenario 3 "styling"

A user:
- [x] 1) should be able to do everything in schenario-2
- [x] 2) should be able to change the font-size of the label
- [x] 3) should be able to change the font-size of the input
#### User scenario 1 "basic"

A user:
- [x] 1) should be able to drag and drop a new asq-multi-choice-q to the canvas
- [x] 2) should be able to change the text of the labels
- [x] 3) should be able to specify a solution
#### User scenario 2 "stats"

A user:
- [ ] 1) should be able to everything in schenario-1
- [ ] 2) should be able to specify an asq-multi-choice-q-stats element that is linked to asq-multi-choice-q
#### User scenario 3 "styling"

A user:
- [ ] 1) should be able to do everything in schenario-2
- [x] 2) should be able to change the font-size of the labels

**Comment by triglian** [comment]
make sure to also have these:
- [x] Prefix elements with qea-
- [ ] add polylint as a task
- [x] make sure there is a JavaScript linter as well
- [x] remove slide references. So far you just have a question editor
- [x] remove slide styling the whole stage should be droppable (same commit as the previous)
- [x] remove scripts
- [x] use ES2016 syntax (with async functions if necessary)
- [x] add tests (different pull request)
- [x] remove purple underline from paper-tabs
- [x] 'select-behavior: findRootNode()' change the function name, is not so good

**Comment by triglian** [comment]
Closing this and will reopen new stats and styling issues when appropriate
